version: '3.4'

services:

  wikiserver:
    container_name: wikiserver
    image: "mcr.microsoft.com/mssql/server:2017-CU8-ubuntu"
    environment: 
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: DevDbP@ssword
    ports: 
      - "5433:1433"
    volumes: 
      - "C:/data/wikiserver/data:/var/opt/mssql/data"

  wiki.api:
    container_name: wikiapi
    image: ${DOCKER_REGISTRY-}wikiapi
    build:
      context: .
      dockerfile: Wiki.API/Dockerfile
    ports: 
      - "5000:80"
      - "5001:443"
    depends_on: 
      - wikiserver
