CREATE TABLE [dbo].[Group]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[UniqueId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[CreatedOn] DATETIMEOFFSET NOT NULL,
);
GO
CREATE INDEX IX_UniqueId
ON [dbo].[Group] ([UniqueId])