CREATE TABLE [dbo].[Group]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UniqueId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[CreatedOn] DATETIMEOFFSET NOT NULL,
);
GO
CREATE NONCLUSTERED INDEX IX_UniqueId 
ON [dbo].[Group] ([UniqueId])