CREATE TABLE [dbo].[Project]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	[CreatedOn] DATETIMEOFFSET NOT NULL,
	[CompanyId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[Company]([Id]),
	[CreatedById] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [dbo].[User]([Id])
);
GO
CREATE INDEX IX_CompanyId 
ON [dbo].[Project] ([CompanyId]);
GO
CREATE INDEX IX_CreatedById
ON [dbo].[Project] ([CreatedById])