CREATE TABLE [dbo].[Tag]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[UniqueId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(15) NOT NULL
);
GO
CREATE INDEX IX_UniqueId
ON [dbo].[Tag] ([UniqueId])
