CREATE TABLE [dbo].[UserProjectScopeMap]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[UniqueId] UNIQUEIDENTIFIER NOT NULL,
	[UniqueUserId] UNIQUEIDENTIFIER NOT NULL,
	[UniqueProjectId] UNIQUEIDENTIFIER NOT NULL,
	[UniqueProjectScopeId] UNIQUEIDENTIFIER NOT NULL
);
GO
CREATE INDEX IX_UniqueId
ON [dbo].[UserProjectScopeMap] ([UniqueId])