CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UniqueId] UNIQUEIDENTIFIER NOT NULL,
	[UserName] NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(500) NOT NULL
);
GO
CREATE NONCLUSTERED INDEX IX_UniqueId 
ON [dbo].[User] ([UniqueId]);