CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UniqueId] UNIQUEIDENTIFIER NOT NULL,
	[UserName] NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(500) NOT NULL,
	[UserRoleId] INT NOT NULL FOREIGN KEY REFERENCES [dbo].[UserRole]([Id]),
);
GO
CREATE NONCLUSTERED INDEX IX_UniqueId 
ON [dbo].[User] ([UniqueId]);
GO
CREATE NONCLUSTERED INDEX IX_UserRoleId 
ON [dbo].[User]([UserRoleId]);