CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[UniqueId] UNIQUEIDENTIFIER NOT NULL,
	[UserName] NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(500) NOT NULL
);
GO
CREATE INDEX IX_UniqueId
ON [dbo].[User] ([UniqueId])