CREATE TABLE [dbo].[Group]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UniqueId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
	[CreatedOn] DATETIMEOFFSET NOT NULL,
	[DomainId] INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Domain]([Id])
);
GO
CREATE NONCLUSTERED INDEX unique_id ON [dbo].[Group] ([UniqueId])
