CREATE TABLE [dbo].[Wiki]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UniqueId] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(MAX) NOT NULL,
	[CreatedOn] DATETIMEOFFSET NOT NULL,
	[ProjectId] INT NOT NULL FOREIGN KEY REFERENCES [dbo].[Project]([Id])
);
GO
CREATE NONCLUSTERED INDEX unique_id ON [dbo].[Wiki] ([UniqueId])
